### ISSUE TITLE
manifold.stream/try-put! to core.async sink throws exception

### ISSUE THREAD

**Issue by mavbozo** [ztellman/manifold#36]
these are my dependencies
```clojure
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [manifold "0.1.0"]]
```
and these are the steps to reproduce the problem

```clojure
> (require '[clojure.core.async :as a])
nil
> (require '[manifold.stream :as s])
nil
> (def c (a/chan))
#'c
> (def si (s/->sink c))
#'si
> @(s/try-put! si ::input 1000 ::timeout)

Exception in thread "async-dispatch-1" java.lang.IllegalArgumentException: No implementation of method: :take! of protocol: #'clojure.core.async.impl.protocols/ReadPort found for class: clojure.lang.Keyword
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
	at clojure.core.async.impl.protocols$eval512$fn__513$G__503__520.invoke(protocols.clj:15)
	at clojure.core.async$do_alts$fn__5334.invoke(async.clj:231)
	at clojure.core.async$do_alts.invoke(async.clj:223)
	at clojure.core.async$ioc_alts_BANG_.doInvoke(async.clj:359)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at manifold.stream.async.CoreAsyncSink$f__8900$fn__8917$state_machine__5209__auto____8918$fn__8920.invoke(async.clj:145)
	at manifold.stream.async.CoreAsyncSink$f__8900$fn__8917$state_machine__5209__auto____8918.invoke(async.clj:145)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
	at manifold.stream.async.CoreAsyncSink$f__8900$fn__8917.invoke(async.clj:145)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ztellman** [comment]
Thanks for the report, this was a blind spot in my tests which has been fixed.
