### ISSUE TITLE
NPE in graph when websocket stream disconnects

### ISSUE THREAD

**Issue by ddossot** [ztellman/manifold#42]
Using `Aleph 0.4.1-alpha1` and `Manifold 0.1.1-alpha2`.

Here is the code that connects a `socket` stream to a `bus` subscription stream:

```clojure
  (s/connect
    (s/filter
      (partial
        room-accept-event?
        idempotent-filter)
      (bus/subscribe
        chatrooms room))
    socket)
```

The filter fn is:
```clojure
(defn- room-accept-event?
  [idempotent-filter event]
  (or
    (nil? event)
    (not (.add idempotent-filter event :ignored))))
```
`idempotent-filter` is a non-nil-safe bounded FIFO map, we accept `nil` values because we think it's the proper indicator of a drained source and want to pass it to the sink.

When a browser window gets brutally closed, the following NPE shows up in the log:
<pre>
[manifold-scheduler-pool-1] 2015-07-22 10:39:54,626 ERROR [manifold.deferred] error in deferred handler
java.lang.NullPointerException
	at manifold.stream.graph$async_connect$this__6562.invoke(graph.clj:183)
	at manifold.stream.graph$async_connect$this__6562$fn__6563$fn__6564.invoke(graph.clj:162)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at manifold.stream.graph$async_connect$this__6562$fn__6563.invoke(graph.clj:162)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__6019.invoke(deferred.clj:398)
	at manifold.deferred.Deferred.success(deferred.clj:398)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:245)
	at manifold.stream.default.Stream.put(default.clj:119)
	at manifold.stream.default.Stream.put(default.clj:141)
	at manifold.stream$filter$fn__7154.invoke(stream.clj:628)
	at manifold.stream.Callback.put(stream.clj:452)
	at manifold.stream.graph$async_send.invoke(graph.clj:50)
	at manifold.stream.graph$async_connect$this__6562.invoke(graph.clj:181)
	at manifold.stream.graph$async_connect$this__6562$fn__6563$fn__6564.invoke(graph.clj:162)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at manifold.stream.graph$async_connect$this__6562$fn__6563.invoke(graph.clj:162)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__6019.invoke(deferred.clj:398)
	at manifold.deferred.Deferred.success(deferred.clj:398)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:245)
	at manifold.stream.default.Stream.put(default.clj:119)
	at manifold.stream.default.Stream.put(default.clj:141)
	at manifold.bus$event_bus$reify__9469$fn__9472.invoke(bus.clj:110)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at manifold.bus$event_bus$reify__9469.publish(bus.clj:110)
	at com.unbounce.events_gateway.server_push$broadcast_heartbeat.invoke(server_push.clj:325)
	at com.unbounce.events_gateway.server_push$make_heartbeater$_heartbeater__11697.invoke(server_push.clj:339)
	at manifold.time$fn__5771$every__5780$f__5781.invoke(time.clj:169)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at manifold.executor$thread_factory$reify__5598$f__5599.invoke(executor.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
</pre>
It happens a few times per closed socket, when `put`s are attempted. Then things clear up internally and the NPE doesn't happen any more.

**Comment by ztellman** [comment]
Hmm, this implies that something in Aleph is returning `nil` when it should be returning a deferred.  I'll look into it, thanks.

**Comment by ztellman** [comment]
I'm fairly sure this should fix it: https://github.com/ztellman/aleph/commit/95e7381948be969ac5ce1fcee390dfad03629e0a.

**Comment by ddossot** [comment]
Confirmed! I've tried a locally built `[aleph "0.4.1-SNAPSHOT"]` with this fix in and the problem is gone.

Thanks a lot.

**Comment by ztellman** [comment]
Thanks for the report.  I'll have to give some thought on how to adequately test for these sorts of cases.
